import { Injectable } from '@angular/core';

export type LanguageCode = 'en' | 'hi' | 'te';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private activeLanguage: LanguageCode = 'en';

  private translations: Record<LanguageCode, Record<string, string>> = {
    en: {
      loginTitle: 'Agriculture Advisor',
      loginSub: 'Smart Crop Recommendation & Advice',
      emailLabel: 'Email Address',
      passwordLabel: 'Password',
      loginBtn: 'Sign In',
      noAccount: "Don't have an account? Register",
      invalidCredentials: 'Invalid Email or Password',
      loginFailed: 'Login Failed',
      loginSuccess: 'Login Successful',
      registerTitle: 'Create Farmer Account',
      nameLabel: 'Full Name',
      mobileLabel: 'Mobile Number',
      registerBtn: 'Register Farmer',
      alreadyAccount: 'Already have an account? Login',
      regSuccess: 'Registration Successful',
      regFailed: 'Registration Failed',
      dashboardTitle: 'Farmer Dashboard',
      welcome: 'Welcome,',
      cropRecBtn: 'Crop Recommendation',
      viewHistoryBtn: 'View History',
      logoutBtn: 'Logout',
      cropRecTitle: 'Crop Recommendation',
      cropRecSub: 'Enter environmental and soil parameters to get optimal crop recommendations.',
      farmerNameLabel: 'Farmer Name',
      soilTypeLabel: 'Soil Type',
      seasonLabel: 'Season',
      selectSoil: 'Select Soil Type',
      selectSeason: 'Select Season',
      tempLabel: 'Temperature (°C)',
      humidityLabel: 'Humidity (%)',
      phLabel: 'pH Level (0-14)',
      rainfallLabel: 'Rainfall (mm)',
      recommendBtn: 'Recommend Crop',
      resultTitle: 'Recommended Crop',
      resultSub: 'Recommended Fertilizer',
      soilBlack: 'Black',
      soilRed: 'Red',
      soilAlluvial: 'Alluvial',
      seasonKharif: 'Kharif',
      seasonRabi: 'Rabi',
      historyTitle: 'Recommendation History',
      historySub: 'List of previous crop recommendation inquiries and environmental parameters.',
      statsTotal: 'Total Queries',
      statsTopCrop: 'Top Recommended Crop',
      statsAvgTemp: 'Avg Temp',
      statsAvgRainfall: 'Avg Rainfall',
      statsAvgPh: 'Avg pH',
      searchPlaceholder: 'Search by Farmer Name or Crop...',
      allSoils: 'All Soil Types',
      allSeasons: 'All Seasons',
      tableFarmer: 'Farmer Name',
      tableSoil: 'Soil Type',
      tableSeason: 'Season',
      tableTemp: 'Temp',
      tableHum: 'Humidity',
      tablePh: 'pH',
      tableRain: 'Rainfall',
      tableCrop: 'Recommended Crop',
      tableFert: 'Fertilizer',
      tableActions: 'Actions',
      deleteConfirm: 'Are you sure you want to delete this record?',
      recordDeleted: 'Record deleted successfully',
      editModalTitle: 'Edit Recommendation Parameters',
      saveBtn: 'Save Changes',
      cancelBtn: 'Cancel',
      noHistory: 'No recommendation history found.',
      cropWheat: 'Wheat',
      cropRice: 'Rice',
      cropCotton: 'Cotton',
      cropMillets: 'Millets',

      fertDAP: 'DAP',
      fertUrea: 'Urea',
      homeTitle: 'Agriculture Advisor',
      homeSub: 'Your intelligent partner for crop recommendation, soil analysis, and fertilizer advisory.',
      homeWelcome: 'Welcome to Agriculture Advisor',
      getStarted: 'Get Started',
      homeLoginCardTitle: 'Already Registered?',
      homeLoginCardDesc: 'Sign in to access your farmer dashboard, submit soil parameters, and view previous crop recommendations.',
      homeRegisterCardTitle: 'New Farmer?',
      homeRegisterCardDesc: 'Register for a new farmer account to request smart crop advice and save recommendation histories.',
      homeThemeTitle: 'Appearance',
      homeLangTitle: 'Preferred Language',
      lightMode: 'Light Mode',
      darkMode: 'Dark Mode'
    },
    hi: {
      loginTitle: 'कृषि सलाहकार',
      loginSub: 'स्मार्ट फसल सिफारिश और सलाह',
      emailLabel: 'ईमेल पता',
      passwordLabel: 'पासवर्ड',
      loginBtn: 'साइन इन करें',
      noAccount: 'खाता नहीं है? पंजीकरण करें',
      invalidCredentials: 'अमान्य ईमेल या पासवर्ड',
      loginFailed: 'लॉगिन विफल रहा',
      loginSuccess: 'लॉगिन सफल',
      registerTitle: 'किसान खाता बनाएं',
      nameLabel: 'पूरा नाम',
      mobileLabel: 'मोबाइल नंबर',
      registerBtn: 'किसान पंजीकरण करें',
      alreadyAccount: 'पहले से ही एक खाता है? लॉगिन करें',
      regSuccess: 'पंजीकरण सफल',
      regFailed: 'पंजीकरण विफल रहा',
      dashboardTitle: 'किसान डैशबोर्ड',
      welcome: 'स्वागत है,',
      cropRecBtn: 'फसल सिफारिश',
      viewHistoryBtn: 'इतिहास देखें',
      logoutBtn: 'लॉगआउट',
      cropRecTitle: 'फसल सिफारिश',
      cropRecSub: 'इष्टतम फसल सिफारिशें प्राप्त करने के लिए पर्यावरणीय और मिट्टी के मापदंड दर्ज करें।',
      farmerNameLabel: 'किसान का नाम',
      soilTypeLabel: 'मिट्टी का प्रकार',
      seasonLabel: 'मौसम',
      selectSoil: 'मिट्टी का प्रकार चुनें',
      selectSeason: 'मौसम चुनें',
      tempLabel: 'तापमान (°C)',
      humidityLabel: 'आर्द्रता (%)',
      phLabel: 'पीएच स्तर (0-14)',
      rainfallLabel: 'वर्षा (mm)',
      recommendBtn: 'फसल की सिफारिश करें',
      resultTitle: 'सिफारिश की गई फसल',
      resultSub: 'सिफारिश की गई खाद',
      soilBlack: 'काली',
      soilRed: 'लाल',
      soilAlluvial: 'जलोढ़',
      seasonKharif: 'खरीफ',
      seasonRabi: 'रबी',
      historyTitle: 'सिफारिश इतिहास',
      historySub: 'पिछली फसल सिफारिश पूछताछ और पर्यावरणीय मापदंडों की सूची।',
      statsTotal: 'कुल प्रश्न',
      statsTopCrop: 'शीर्ष अनुशंसित फसल',
      statsAvgTemp: 'औसत तापमान',
      statsAvgRainfall: 'औसत वर्षा',
      statsAvgPh: 'औसत पीएच',
      searchPlaceholder: 'किसान के नाम या फसल से खोजें...',
      allSoils: 'सभी मिट्टी के प्रकार',
      allSeasons: 'सभी मौसम',
      tableFarmer: 'किसान का नाम',
      tableSoil: 'मिट्टी का प्रकार',
      tableSeason: 'मौसम',
      tableTemp: 'तापमान',
      tableHum: 'आर्द्रता',
      tablePh: 'पीएच',
      tableRain: 'वर्षा',
      tableCrop: 'अनुशंसित फसल',
      tableFert: 'अनुशंसित खाद',
      tableActions: 'कार्रवाई',
      deleteConfirm: 'क्या आप वाकई इस रिकॉर्ड को हटाना चाहते हैं?',
      recordDeleted: 'रिकॉर्ड सफलतापूर्वक हटा दिया गया',
      editModalTitle: 'सिफारिश मापदंडों को संपादित करें',
      saveBtn: 'बदलाव सहेजें',
      cancelBtn: 'रद्द करें',
      noHistory: 'कोई सिफारिश इतिहास नहीं मिला।',
      cropWheat: 'गेहूं',
      cropRice: 'धान',
      cropCotton: 'कपास',
      cropMillets: 'मोटा अनाज',

      fertDAP: 'डीएपी',
      fertUrea: 'यूरिया',
      homeTitle: 'कृषि सलाहकार',
      homeSub: 'फसल की सिफारिश, मिट्टी के विश्लेषण और उर्वरक सलाह के लिए आपका बुद्धिमान भागीदार।',
      homeWelcome: 'कृषि सलाहकार में आपका स्वागत है',
      getStarted: 'शुरू करें',
      homeLoginCardTitle: 'पहले से पंजीकृत हैं?',
      homeLoginCardDesc: 'अपने किसान डैशबोर्ड तक पहुंचने, मिट्टी के मापदंडों को सबमिट करने और पिछली फसल सिफारिशों को देखने के लिए साइन इन करें।',
      homeRegisterCardTitle: 'नए किसान?',
      homeRegisterCardDesc: 'स्मार्ट फसल सलाह का अनुरोध करने और सिफारिशों के इतिहास को सहेजने के लिए एक नया किसान खाता पंजीकृत करें।',
      homeThemeTitle: 'थीम (सजावट)',
      homeLangTitle: 'पसंदीदा भाषा',
      lightMode: 'लाइट मोड',
      darkMode: 'डार्क मोड'
    },
    te: {
      loginTitle: 'వ్యవసాయ సలహాదారు',
      loginSub: 'స్మార్ట్ పంట సిఫార్సు & సలహా',
      emailLabel: 'ఈమెయిల్ చిరునామా',
      passwordLabel: 'పాస్ వర్డ్',
      loginBtn: 'సైన్ ఇన్',
      noAccount: 'ఖాతా లేదా? రిజిస్టర్ చేసుకోండి',
      invalidCredentials: 'చెల్లని ఈమెయిల్ లేదా పాస్ వర్డ్',
      loginFailed: 'లాగిన్ విఫలమైంది',
      loginSuccess: 'లాగిన్ విజయవంతమైంది',
      registerTitle: 'రైతు ఖాతా సృష్టించండి',
      nameLabel: 'పూర్తి పేరు',
      mobileLabel: 'మొబైల్ సంఖ్య',
      registerBtn: 'రైతు రిజిస్ట్రేషన్',
      alreadyAccount: 'ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి',
      regSuccess: 'రిజిస్ట్రేషన్ విజయవంతమైంది',
      regFailed: 'రిజిస్ట్రేషన్ విఫలమైంది',
      dashboardTitle: 'రైతు డాష్ బోర్డ్',
      welcome: 'స్వాగతం,',
      cropRecBtn: 'పంట సిఫార్సు',
      viewHistoryBtn: 'చరిత్రను వీక్షించండి',
      logoutBtn: 'లాగ్ అవుట్',
      cropRecTitle: 'పంట సిఫార్సు',
      cropRecSub: 'అనుకూలమైన పంట సిఫార్సులను పొందడానికి పర్యావరణ మరియు నేల పారామితులను నమోదు చేయండి.',
      farmerNameLabel: 'రైతు పేరు',
      soilTypeLabel: 'నేల రకం',
      seasonLabel: 'సీజన్',
      selectSoil: 'నేల రకాన్ని ఎంచుకోండి',
      selectSeason: 'సీజన్ ఎంచుకోండి',
      tempLabel: 'ఉష్ణోగ్రత (°C)',
      humidityLabel: 'తేమ (%)',
      phLabel: 'pH స్థాయి (0-14)',
      rainfallLabel: 'వర్షపాతం (mm)',
      recommendBtn: 'పంటను సిఫార్సు చేయి',
      resultTitle: 'సిఫార్సు చేయబడిన పంట',
      resultSub: 'సిఫార్సు చేయబడిన ఎరువు',
      soilBlack: 'నల్ల నేల',
      soilRed: 'ఎర్ర నేల',
      soilAlluvial: 'ఒండ్రు నేల',
      seasonKharif: 'ఖరీఫ్',
      seasonRabi: 'రబీ',
      historyTitle: 'సిఫార్సుల చరిత్ర',
      historySub: 'మునుపటి పంట సిఫార్సుల విచారణలు మరియు పర్యావరణ పారామితుల జాబితా.',
      statsTotal: 'మొత్తం ప్రశ్నలు',
      statsTopCrop: 'ఎక్కువ సిఫార్సు చేసిన పంట',
      statsAvgTemp: 'సగటు ఉష్ణోగ్రత',
      statsAvgRainfall: 'సగటు వర్షపాతం',
      statsAvgPh: 'సగటు pH',
      searchPlaceholder: 'రైతు పేరు లేదా పంట ద్వారా శోధించండి...',
      allSoils: 'అన్ని నేల రకాలు',
      allSeasons: 'అన్ని సీజన్లు',
      tableFarmer: 'రైతు పేరు',
      tableSoil: 'నేల రకం',
      tableSeason: 'సీజన్',
      tableTemp: 'ఉష్ణోగ్రత',
      tableHum: 'తేమ',
      tablePh: 'pH',
      tableRain: 'వర్షపాతం',
      tableCrop: 'సిఫార్సు చేసిన పంట',
      tableFert: 'సిఫార్సు చేసిన ఎరువు',
      tableActions: 'చర్యలు',
      deleteConfirm: 'మీరు నిజంగా ఈ రికార్డును తొలగించాలనుకుంటున్నారా?',
      recordDeleted: 'రికార్డు విజయవంతంగా తొలగించబడింది',
      editModalTitle: 'సిఫార్సు పారామితులను సవరించండి',
      saveBtn: 'మార్పులను సేవ్ చేయి',
      cancelBtn: 'రద్దు చేయి',
      noHistory: 'సిఫార్సుల చరిత్ర కనుగొనబడలేదు.',
      cropWheat: 'గోధుమ',
      cropRice: 'వరి',
      cropCotton: 'పత్తి',
      cropMillets: 'సిరిధాన్యాలు',

      fertDAP: 'డీఏపీ',
      fertUrea: 'యూరియా',
      homeTitle: 'వ్యవసాయ సలహాదారు',
      homeSub: 'పంట సిఫార్సు, నేల విశ్లేషణ మరియు ఎరువుల సలహా కోసం మీ తెలివైన భాగస్వామి.',
      homeWelcome: 'వ్యవసాయ సలహాదారుకు స్వాగతం',
      getStarted: 'ప్రారంభించండి',
      homeLoginCardTitle: 'ఇప్పటికే నమోదు చేసుకున్నారా?',
      homeLoginCardDesc: 'మీ రైతు డ్యాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి, నేల పారామితులను సమర్పించడానికి మరియు మునుపటి పంట సిఫార్సులను చూడటానికి లాగిన్ అవ్వండి.',
      homeRegisterCardTitle: 'కొత్త రైతా?',
      homeRegisterCardDesc: 'స్మార్ట్ పంట సలహాలను అభ్యర్థించడానికి మరియు సిఫార్సుల చరిత్రను సేవ్ చేయడానికి కొత్త రైతు ఖాతాను నమోదు చేసుకోండి.',
      homeThemeTitle: 'రంగు థీమ్',
      homeLangTitle: 'భాషా ఎంపిక',
      lightMode: 'లైట్ మోడ్',
      darkMode: 'డార్క్ మోడ్'
    }
  };

  constructor() {
    const saved = localStorage.getItem('appLang');
    if (saved === 'en' || saved === 'hi' || saved === 'te') {
      this.activeLanguage = saved;
    }
  }

  getCurrentLanguage(): LanguageCode {
    return this.activeLanguage;
  }

  setLanguage(lang: LanguageCode): void {
    this.activeLanguage = lang;
    localStorage.setItem('appLang', lang);
  }

  get t(): any {
    return this.translations[this.activeLanguage];
  }
}
